package dev.aisandbox.demo.twisty.rules.cube222;

public enum CornerPosition {
  // CORNER POSITIONS
  CORNER_FRONT_TOP_LEFT,
  CORNER_TOP_LEFT_FRONT,
  CORNER_LEFT_FRONT_TOP,

  CORNER_FRONT_RIGHT_TOP,
  CORNER_RIGHT_TOP_FRONT,
  CORNER_TOP_FRONT_RIGHT,

  CORNER_RIGHT_BACK_TOP,
  CORNER_BACK_TOP_RIGHT,
  CORNER_TOP_RIGHT_BACK,

  CORNER_BACK_LEFT_TOP,
  CORNER_LEFT_TOP_BACK,
  CORNER_TOP_BACK_LEFT,

  CORNER_FRONT_BOTTOM_RIGHT,
  CORNER_BOTTOM_RIGHT_FRONT,
  CORNER_RIGHT_FRONT_BOTTOM,

  CORNER_FRONT_LEFT_BOTTOM,
  CORNER_LEFT_BOTTOM_FRONT,
  CORNER_BOTTOM_FRONT_LEFT,

  CORNER_BACK_RIGHT_BOTTOM,
  CORNER_RIGHT_BOTTOM_BACK,
  CORNER_BOTTOM_BACK_RIGHT,

  CORNER_BACK_BOTTOM_LEFT,
  CORNER_BOTTOM_LEFT_BACK,
      CORNER_LEFT_BACK_BOTTOM

}
