package dev.aisandbox.demo.twisty.rules.cube333;

public enum EdgePosition {
  // EDGE POSITIONS
  EDGE_TOP_FRONT,
  EDGE_TOP_BACK,
  EDGE_TOP_LEFT,
  EDGE_TOP_RIGHT,
  EDGE_BACK_TOP,
  EDGE_BACK_LEFT,
  EDGE_BACK_RIGHT,
  EDGE_BACK_BOTTOM,
  EDGE_FRONT_RIGHT,
  EDGE_FRONT_TOP,
  EDGE_FRONT_LEFT,
  EDGE_FRONT_BOTTOM,
  EDGE_LEFT_TOP,
  EDGE_LEFT_BACK,
  EDGE_LEFT_FRONT,
  EDGE_LEFT_BOTTOM,
  EDGE_RIGHT_TOP,
  EDGE_RIGHT_BACK,
  EDGE_RIGHT_BOTTOM,
  EDGE_RIGHT_FRONT,
  EDGE_BOTTOM_FRONT,
  EDGE_BOTTOM_RIGHT,
  EDGE_BOTTOM_BACK,
  EDGE_BOTTOM_LEFT,


}
